name: build and test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:

  buildandtest:
    name: Build and Test on Go ${{matrix.go}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21', '1.20' ]
    steps:
      - name: Set up Go ${{matrix.go}}
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # pin@v4
        with:
          go-version: ${{matrix.go}}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # pin@v4

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test Go packages as root
        run: go test -v -p 1 -race  -exec sudo ./...

      - name: Test Go packages as ordinary user
        run: go test -v -p 1 -race ./...
