name: build and test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:

  buildandtest:
    name: Build and Test on Go ${{matrix.go}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 'stable', 'oldstable' ]
    steps:
      - name: Set up Go ${{matrix.go}}
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # pin@v5
        with:
          go-version: ${{matrix.go}}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test Go packages as root
        run: go test -v -p 1 -race  -exec sudo ./...

      - name: Test Go packages as ordinary user
        run: go test -v -p 1 -race ./...
